services:
  - type: web
    runtime: static
    name: songstreet-io
    repo: https://github.com/songstreetadmin/songstreet-io
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
